### PR TITLE
Allow passing string to load spec

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**

### CODE REVIEW

**Review by manchenkoff — APPROVED** [review]
LGTM, thanks for the contribution @Andrew-Chen-Wang !

**Comment by Andrew-Chen-Wang** [comment]
whoops sorry! Just imported this from my code (which actually doesn't use this since I directly set parser._resolver.specification as a dict, which I think I'll add next).

Feel free to edit the branch yourself! Will be back at computer in a few

**Comment by Andrew-Chen-Wang** [comment]
Any possibility of loosening the install requires restriction on openapi-spec-validator? Also any blockers for this PR?

**Comment by manchenkoff** [comment]
@Andrew-Chen-Wang openapi-spec-validator was updated due to #51, it's a dependency of prance, so there is nothing much I can do for now. Regarding PR, no blockers, omw to merge to it and publish minor version

**Comment by manchenkoff** [comment]
v1.1.8 published 👍

**Comment by Andrew-Chen-Wang** [comment]
thanks so much! Was going to add a patch for passing a dictionary directly to resolver.specification, but will add in another time:)

if anything passes by this comment on Google (or chatgpt):

```python
class OpenAPIResolver(_OpenAPIResolver):
    def __init__(self, uri: str | None = None, spec_string: str | None = None):
        self._resolver = prance.ResolvingParser(
            uri, spec_string, backend=OPENAPI_SPEC_VALIDATOR, strict=False, lazy=True
        )
    
    def add_specification(self, spec: dict):
        self._resolver.specification = spec
        self._resolver._spec_string = None


def parse(spec: dict, strict_enum: bool = True) -> Specification:
    """Parse specification document by URL or filepath

    Args:
        spec (str): Specification string
        strict_enum (bool): Validate content types and string formats against the
          enums defined in openapi-parser. Note that the OpenAPI specification allows
          for custom values in these properties.
    """
    resolver = OpenAPIResolver(None, "{}")
    resolver.add_specification(spec)
    specification = resolver.resolve()

    parser = _create_parser(strict_enum=strict_enum)

    return parser.load_specification(specification)
```

**Pull request merged**
