### PR TITLE
feat: add #/components/schemas parsing to retrieve explicit schema

### PR DESCRIPTION
**Pull request by johmau**
As "securitySchema", parsing "schemas" would be great.
I'm using it for own code generation plugin.
It would be cool if you put it in the mainline.

Thx

### CODE REVIEW

**Comment by manchenkoff** [comment]
Hey @johmau, thanks for contributing! I also use this package for code-generation stuff, so I have a question regarding your changes. Since you have **schemas** in the **components** section you probably use them in some endpoints' schemas. Could you describe the case when you need schemas from **components** instead of **paths**?

**Comment by johmau** [comment]
@manchenkoff I use those schemas to generate specific input classes for my cpp web framework, with that I can create a class named Uuid for example and differenciate the name from the property in the endpoint itself. If I use the property name I'm forced to use a class name based on the property name, then If I've several Uuid in my endpoint, I will have several class declaration althought there the same structure and I won't be able to extends them afterward.

**Comment by manchenkoff** [comment]
Agree, for now this is fine solution, but I had another idea - to parse it with names for endpoints as well, but I need to make some changes in the external package first. So, I left some comments and I'll be ready to merge once you fixed it 👍

**Comment by johmau** [comment]
@manchenkoff Ok great !

**Review by manchenkoff — CHANGES_REQUESTED** [review]

**Review by manchenkoff — APPROVED** [review]

**Comment by manchenkoff** [comment]
Hey @johmau, please, check CI report, there is some broken unit test. I assume that is because of new parameter in the constructor method.

**Comment by johmau** [comment]
@manchenkoff Forgot unit test Fuuu let's fix that

**Comment by manchenkoff** [comment]
@johmau , v1.1.2 version has been published to PyPi, thanks 👍

**Pull request merged**
